### ISSUE TITLE
Request help for: KrakenAPIError: ['EGeneral:Invalid arguments:ordertype']

### ISSUE THREAD

**Issue by xaviersoto** [dominiktraxl/pykrakenapi#9]
Dominik,

     Hi, thanks for the awesome library, I was hoping you could help me understand why do I keep getting the Error: invalid arguments: 'ordertype' ?
my args for k.add_standard_order()  would be:
('xbtusd', 'buy', 'limit', '.002', price='8900', leverage='5', validate=True, trading_agreement='agree')
 Is there a way for me to validate my function call without testing using live execution?
Thanks in advance,
Xavier

**Comment by xaviersoto** [comment]
I just took another look at the help(KrakenAPI) output and I see that:
validate=True, allows me to validate a function call without live execution of the order.
perhaps the __self__ default tier=3 may be causing this 'ordertype' error, because I may not be tier 3 yet.

**Comment by dominiktraxl** [comment]
Hi, I tried calling `k.add_standard_order('xbtusd', 'buy', 'limit', '.002', price='8900', leverage='5', validate=True, trading_agreement='agree')` (same arguments you used), and it worked. I don't know why you are getting a "Error: invalid arguments: 'ordertype'".  It does not have to do with the tier you can set when initiating KrakenAPI, because that only affects the call rate limiter. If you keep getting that error, could you please send the code you're using?

**Comment by xaviersoto** [comment]
Thank you, I didn't even try that, felt foolish, but relieved now, because It WORKS!
Although the error was raised for 'ordertype' I found the working call has price passed as an argument '8990' rather than as a parameter price='8990' my call works in this form: 
k.add_standard_order('xbtusd', 'buy', 'limit', '.002', '8900', leverage='5', validate=True, trading_agreement='agree')  Really appreciate the quick response.

**Comment by dominiktraxl** [comment]
No worries, good to hear it works.
